[Octo settings]
APP_ID = 400
CLIENT_SECRET_KEY = 0jv0wsohnnsigttbfigushbtl3a8m7l5
VERSION = 705100
URL = https://api.asset.game-gakuen-idolmaster.jp/
A = x5HFaJCJywDyuButLM0f

[Download settings]
# set `UPDATE` to `True` for copy the downloaded files from update path to default store
# path or `False` to move (The default value for first download is False).
UPDATE_FLAG = False
MAX_RETRIES = 5

[Path settings]
ASSET_PATH = cache/asset
RESOURCE_PATH = cache/resource
UPDATE_PATH = cache/update

[Unity settings]
UNITY_SIGNATURE = Unity
UNITY_VERSION = 6
