syntax = "proto3";
package pcommon;
option go_package = "vertesan/campus/proto/pcommon";
import "penum.proto";

message Achievement {
  string achievementId = 1;
  int32 threshold = 2;
}
message AntiCheatCriticalResult {
  repeated AntiCheatCriticalResult.Record records = 1;
  repeated AntiCheatCriticalResult.Log logs = 2;
  message Log {
    string id = 1;
    repeated string lines = 10;
  }
  message Record {
    string tag = 1;
    string id = 2;
    string expected = 3;
    string actual = 4;
  }
}
message AntiCheatSummaryResult {
  repeated AntiCheatSummaryResult.Score scores = 1;
  message Score {
    string id = 1;
    int32 calculatedScore = 2;
    int32 loggedScore = 3;
  }
}
message AuditionNpcResult {
  int32 number = 1;
  int32 score = 2;
  int32 point = 3;
}
message CoinGasha {
  string id = 1;
  penum.CoinGashaType type = 2;
  string name = 3;
  string description = 4;
  string assetId = 5;
  string coinGashaButtonId = 6;
  int32 featureRewardResetDay = 7;
  repeated CoinGashaReward featureGashaRewards = 8;
  repeated CoinGashaReward commonGashaRewards = 9;
  repeated CoinGashaBox prevBoxList = 10;
  repeated CoinGashaBox nextBoxList = 11;
  penum.CoinGashaBoxResetTypeType boxResetType = 12;
  int32 resetCount = 13;
  bool isResettable = 14;
  int32 totalDrawCount = 15;
  repeated CoinGashaDrawCountReward drawCountRewards = 16;
  int32 maxGuaranteedDrawCount = 17;
  bool unlock = 50;
  string viewConditionSetId = 51;
  string unlockConditionSetId = 52;
  int64 startTime = 100;
  int64 endTime = 101;
  int32 order = 102;
}
message CoinGashaBox {
  repeated CoinGashaReward featureGashaRewards = 1;
  repeated CoinGashaReward commonGashaRewards = 2;
}
message CoinGashaDrawCountReward {
  int32 drawCount = 1;
  Reward reward = 2;
}
message CoinGashaReward {
  Reward reward = 1;
  int32 remainingDrawCount = 2;
  int32 maxEmissionCount = 3;
  bool isPickup = 4;
}
message CompetitionDeck {
  repeated CompetitionStage stages = 1;
}
message CompetitionDeckSetup {
  repeated CompetitionDeckSetup.Stage stages = 1;
  message Stage {
    penum.CompetitionStageType stageType = 1;
    repeated CompetitionDeckSetupMemorySlot slots = 2;
  }
}
message CompetitionDeckSetupMemorySlot {
  penum.CompetitionStageSectionType sectionType = 1;
  ContestDeckMemorySetup mainMemory = 2;
  ContestDeckMemorySetup subMemory = 3;
}
message CompetitionStage {
  penum.CompetitionStageType stageType = 1;
  repeated ExamContestSection sections = 2;
}
message ConsumptionResult {
  penum.ResourceType resourceType = 1;
  string resourceId = 2;
  int64 quantity = 3;
  int64 beforeQuantity = 4;
  int64 afterQuantity = 5;
}
message ContestDeckMemory {
  Memory memory = 1;
  repeated string activeProduceCardIds = 2;
}
message ContestDeckMemorySetup {
  string userMemoryId = 1;
  repeated string activeProduceCardIds = 2;
}
message Event {
  penum.EventType eventType = 1;
  string eventId = 2;
  string eventName = 14;
  string homeIconAssetId = 3;
  string bannerAssetId = 4;
  bool noti = 5;
  string dailyMissionGroupId = 6;
  string missionGroupId = 7;
  string missionDailyReleaseGroupId = 8;
  string missionPanelSheetGroupId = 9;
  string storyGroupId = 10;
  string itemId = 11;
  string playItemId = 15;
  repeated string characterIds = 12;
  repeated string dearnessMissionPanelSheetGroupIds = 13;
  int64 startTime = 100;
  int64 endTime = 101;
  int64 fixRankTime = 99;
  int64 closeTime = 102;
  int32 priority = 103;
}
message EventBonus {
  repeated EventBonus.EventCharacterBonus characterBonuses = 1;
  repeated EventBonus.EventIdolCardBonus idolCardBonuses = 2;
  repeated EventBonus.EventSupportCardBonus supportCardBonuses = 3;
  message EventPotentialRankBonusPermil {
    penum.IdolCardPotentialRank potentialRank = 1;
    int32 permil = 2;
  }
  message EventLevelLimitRankBonusPermil {
    penum.SupportCardLevelLimitRank levelLimitRank = 1;
    int32 permil = 2;
  }
  message EventCharacterBonus {
    repeated string characterIds = 1;
    int32 permil = 2;
    repeated penum.IdolCardRarity idolCardRarities = 3;
    repeated EventBonus.EventPotentialRankBonusPermil potentialRankBonusPermils = 4;
  }
  message EventIdolCardBonus {
    repeated string idolCardIds = 1;
    repeated EventBonus.EventPotentialRankBonusPermil potentialRankBonusPermils = 2;
  }
  message EventSupportCardBonus {
    repeated string supportCardIds = 1;
    repeated EventBonus.EventLevelLimitRankBonusPermil levelLimitRankBonusPermils = 2;
  }
}
message ExamAction {
  penum.ExamActionType actionType = 1;
  repeated int32 indexes = 2;
}
message ExamAiBaseModel {
  string modelVersion = 1;
  string env = 3;
  string tag = 4;
  string masterVersion = 5;
  string name = 6;
  string machineType = 7;
  int32 trainingCount = 8;
  penum.ProducePlanType planType = 50;
}
message ExamAntiCheatTarget {
  repeated penum.ExamGameType features = 1;
  repeated string dates = 2;
  repeated string userIds = 3;
  repeated string logIds = 4;
}
message ExamBattleAutoPlayer {
  string characterId = 1;
  string idolCardId = 2;
  penum.ProducePlanType planType = 3;
  penum.ProduceExamEffectType examEffectType = 4;
  penum.IdolCardLevelLimitRank idolCardLevelLimitRank = 5;
  penum.IdolCardPotentialRank idolCardPotentialRank = 6;
  int32 power = 7;
  bool isPrimaStella = 8;
  int64 seed = 50;
  int32 vocal = 51;
  int32 dance = 52;
  int32 visual = 53;
  int32 vocalBonusPermil = 54;
  int32 danceBonusPermil = 55;
  int32 visualBonusPermil = 56;
  int32 maxStamina = 57;
  repeated ProduceCard produceCards = 58;
  repeated string produceItemIds = 59;
  repeated string produceCustomizeItemIds = 60;
  int32 rank = 100;
  int32 score = 101;
  int32 vocalScore = 102;
  int32 danceScore = 103;
  int32 visualScore = 104;
  repeated int32 selectIndexList = 105;
}
message ExamBattleAutoRequest {
  string appVersion = 1;
  string masterVersion = 2;
  string masterHash = 3;
  int32 vocal = 4;
  int32 dance = 5;
  int32 visual = 6;
  string examSettingId = 7;
  repeated ExamBattleAutoStage stages = 8;
}
message ExamBattleAutoStage {
  int32 limitTurn = 1;
  string produceExamGimmickEffectGroupId = 2;
  repeated ExamBattleAutoPlayer selfPlayers = 3;
  repeated ExamBattleAutoPlayer rivalPlayers = 4;
  int32 vocal = 5;
  int32 dance = 6;
  int32 visual = 7;
}
message ExamBattleAutoStageResult {
  repeated ExamBattleAutoStageResult.Player selfPlayers = 3;
  repeated ExamBattleAutoStageResult.Player rivalPlayers = 4;
  message Player {
    int32 score = 1;
    int32 vocalScore = 2;
    int32 danceScore = 3;
    int32 visualScore = 4;
    repeated int32 list = 5;
  }
}
message ExamBattleResult {
  int32 rank = 1;
  int32 score = 2;
  int32 stamina = 3;
  repeated string produceDrinkIds = 5;
  repeated ProduceItem produceItems = 6;
  repeated ExamTriggerCount examTriggerCounts = 7;
  int32 vocalScore = 8;
  int32 danceScore = 9;
  int32 visualScore = 10;
  repeated ExamAction examActions = 100;
}
message ExamCommandLog {
  penum.ExamCommandType commandType = 1;
  penum.ExamPhaseType phaseType = 2;
  repeated int32 selectIndexes = 3;
  int32 useIndex = 4;
  ProduceCard useProduceCard = 5;
  string useProduceDrinkId = 6;
}
message ExamContestCommand {
  penum.ExamCommandType commandType = 1;
  penum.ExamPhaseType phaseType = 2;
  repeated ExamAction examActions = 10;
  ProduceCard useProduceCard = 20;
  string useProduceDrinkId = 21;
}
message ExamContestPlayer {
  int64 seed = 1;
  string characterId = 10;
  string idolCardId = 11;
  penum.ProduceExamEffectType examEffectType = 12;
  penum.IdolCardLevelLimitRank idolCardLevelLimitRank = 13;
  penum.IdolCardPotentialRank idolCardPotentialRank = 14;
  bool isPrimaStella = 15;
  int32 power = 16;
  string idolCardSkinId = 17;
  int32 vocal = 50;
  int32 dance = 51;
  int32 visual = 52;
  int32 vocalBonusPermil = 53;
  int32 danceBonusPermil = 54;
  int32 visualBonusPermil = 55;
  int32 maxStamina = 56;
  repeated ProduceCard produceCards = 57;
  repeated ProduceItem produceItems = 58;
  repeated string produceCustomizeItemIds = 59;
  repeated string produceDrinkIds = 60;
  repeated ExamSupportCard supportCards = 61;
  int32 stamina = 62;
  repeated ExamAction examActions = 100;
}
message ExamContestPlayerResult {
  int32 score = 1;
  bool isAuto = 2;
  int32 stamina = 20;
  repeated ProduceItem produceItems = 21;
  repeated ExamContestTurn examContestTurns = 50;
}
message ExamContestResult {
  repeated ExamContestStageResult stages = 1;
}
message ExamContestSection {
  int32 limitTurn = 1;
  string produceExamGimmickEffectGroupId = 2;
  ExamContestPlayer player = 3;
}
message ExamContestSectionResult {
  ExamContestPlayerResult player = 1;
}
message ExamContestSituation {
  string appVersion = 1;
  string imageVersion = 2;
  string masterVersion = 3;
  string masterHash = 4;
  int32 vocal = 10;
  int32 dance = 11;
  int32 visual = 12;
  string examSettingId = 13;
  repeated ExamContestStage stages = 14;
}
message ExamContestStage {
  penum.ProducePlanType planType = 1;
  string produceExamGimmickEffectGroupId = 2;
  repeated ProduceItem stageProduceItems = 3;
  string produceExamBattleNpcGroupId = 4;
  int32 forceEndScore = 5;
  repeated ExamContestSection selfSections = 10;
  repeated ExamContestSection rivalSections = 11;
  repeated string researchExternalProduceCardIds = 100;
  repeated ExamStatusEnchant examStatusEnchants = 110;
  repeated ExamStatusEnchant examPermanentStatusEnchants = 111;
}
message ExamContestStageResult {
  repeated ExamContestSectionResult selfSections = 1;
  repeated ExamContestSectionResult rivalSections = 2;
}
message ExamContestTurn {
  int32 turn = 1;
  repeated ExamContestCommand examContestCommands = 10;
  int32 score = 50;
  int32 additionScore = 51;
  int32 stamina = 52;
  int32 consumedStamina = 53;
  int32 block = 54;
  int32 additionBlock = 55;
  repeated string triggeredStatusEnchantIds = 56;
  penum.ProduceParameterType parameterType = 57;
  penum.ExamIdolStatusType idolStatusType = 58;
  int32 idolStatusStepCount = 59;
  repeated ProduceCard startPlayHandProduceCards = 60;
  repeated ProduceCard startPlayHoldProduceCards = 61;
  repeated ExamStatusEffect startPlayStatuses = 62;
}
message ExamStatusEffect {
  penum.ExamStatusEffectType statusEffectType = 1;
  int32 value = 2;
  int32 turn = 3;
  bool isPassingTurnStart = 4;
}
message ExamStatusEnchant {
  penum.ProduceTriggerOriginType originType = 1;
  string originOwnerId = 2;
  string originId = 3;
  int32 originLevel = 4;
  string id = 5;
}
message ExamSupportCard {
  string supportCardId = 1;
  int32 produceCardUpgradePermil = 2;
}
message ExamTriggerCount {
  string produceExamTriggerId = 1;
  int32 count = 2;
}
message ExamTurnEndLog {
  int32 turn = 1;
  int32 score = 2;
  int32 stamina = 3;
  int32 consumedStamina = 4;
  int32 block = 5;
  int32 additionBlock = 6;
  penum.ProduceParameterType parameterType = 7;
  penum.ExamIdolStatusType idolStatusType = 8;
  int32 idolStatusStepCount = 9;
  repeated ProduceCard startPlayHandProduceCards = 50;
  repeated string startPlayStatuses = 51;
  repeated ProduceCard startPlayHoldProduceCards = 52;
  repeated ExamCommandLog commands = 100;
}
message Gasha {
  string id = 1;
  penum.GashaType type = 2;
  string name = 3;
  string description = 4;
  repeated GashaButton gashaButtons = 5;
  GashaStepUp gashaStepUp = 6;
  GashaSelectPickup gashaSelectPickup = 7;
  GashaContinuous gashaContinuous = 8;
  GashaStepUpSelectPickup gashaStepUpSelectPickup = 9;
  string gashaCardBonusId = 20;
  GashaPoint gashaPoint = 21;
  repeated Reward bonusRewards = 22;
  string bannerAssetId = 24;
  string bannerLabelAssetId = 25;
  string movieAssetId = 26;
  string screenAssetId = 27;
  string appealTextAssetId = 28;
  string noticeId = 29;
  string viewConditionSetId = 30;
  string unlockConditionSetId = 31;
  bool hasIdolCard = 32;
  repeated string pickupIdolCardSkinIds = 40;
  repeated string pickupSupportCardIds = 41;
  repeated string pickupProduceCardSkinIds = 46;
  repeated GashaBackgroundPickup backgroundPickupIdolCardSkins = 42;
  repeated GashaBackgroundPickup backgroundPickupSupportCards = 43;
  repeated GashaBackgroundPickup backgroundPickupProduceCardSkins = 47;
  string animationBackgroundAssetId = 44;
  string bgmAssetId = 45;
  int64 startTime = 100;
  int64 endTime = 101;
  int32 order = 102;
}
message GashaBackgroundPickup {
  string idolCardSkinId = 1;
  string supportCardId = 2;
  string produceCardSkinId = 6;
  string movieAssetId = 3;
  string screenAssetId = 4;
  repeated Reward rewards = 5;
}
message GashaBanner {
  string gashaId = 1;
  string bannerAssetId = 2;
  string name = 3;
  int64 endTime = 100;
  int32 order = 101;
}
message GashaButton {
  string id = 1;
  int32 remainingDrawCount = 2;
  int32 remainingDiscountDrawCount = 3;
}
message GashaContinuous {
  bool isContinued = 1;
  int32 sharedContinuedCount = 2;
  int32 sharedDrawRewardCount = 3;
  repeated Reward sharedRewards = 4;
}
message GashaPoint {
  string gashaPointId = 1;
  int32 point = 2;
  bool exchangeable = 3;
  string name = 4;
  int32 minRequire = 5;
  int64 endTime = 101;
}
message GashaSelectPickup {
  repeated string idolCardSkinIds = 2;
  repeated string supportCardIds = 3;
  repeated string produceCardSkinIds = 7;
  repeated Reward pickupRewards = 4;
  int32 pickupCount = 5;
  int32 drawCount = 6;
}
message GashaStepUp {
  int32 number = 1;
  bool isLimited = 2;
  repeated GashaStepUpStep steps = 3;
}
message GashaStepUpSelectPickup {
  int32 number = 1;
  bool isLimited = 2;
  bool isCommon = 3;
  repeated GashaStepUpSelectPickupStep steps = 4;
}
message GashaStepUpSelectPickupStep {
  int32 number = 1;
  string gashaButtonId = 2;
  string stepLabelColor = 3;
  string appealAssetId = 4;
  bool isFeature = 5;
  repeated Reward bonusRewards = 6;
  repeated Reward pickupRewards = 7;
  int32 pickupCount = 20;
  repeated string idolCardSkinIds = 21;
  repeated string supportCardIds = 22;
  repeated string produceCardSkinIds = 23;
}
message GashaStepUpStep {
  int32 number = 1;
  string stepLabelColor = 2;
  string appealAssetId = 3;
  bool isFeature = 4;
  repeated Reward bonusRewards = 5;
  string gashaButtonId = 6;
}
message GuildMission {
  int32 number = 1;
  string storyEventGuildMissionId = 2;
  string produceConditionSetDescription1 = 3;
  string produceConditionSetDescription2 = 4;
  string produceConditionSetDescription3 = 5;
  int32 produceConditionSetCount = 6;
  int32 threshold = 7;
  int32 progress = 8;
  Reward reward = 9;
  bool received = 10;
  SimpleProfile mvpProfile = 11;
  GuildMission.Icon icon = 12;
  message Icon {
    penum.ProduceConditionType type = 1;
    string resourceId1 = 2;
    string resourceId2 = 3;
    penum.ResultGrade grade = 4;
  }
}
message GuildMissionHistory {
  int32 number = 1;
  string storyEventGuildMissionId = 2;
  SimpleProfile profile = 3;
  penum.GuildMissionPhaseType phaseType = 4;
  int64 progressedTime = 5;
}
message GvgRaidGuild {
  string name = 1;
  Achievement achievement = 2;
  int32 point = 3;
  int32 rank = 4;
}
message GvgRaidSetUpDeck {
  repeated GvgRaidSlot slots = 1;
}
message GvgRaidSlot {
  string mainUserMemoryId = 1;
  repeated string subUserMemoryIds = 2;
}
message HomeBanner {
  string assetId = 1;
  penum.LinkType linkType = 2;
  string linkId = 3;
  string viewConditionSetId = 7;
  int64 startTime = 4;
  int64 endTime = 5;
  int32 priority = 6;
}
message HomeNavigation {
  string description = 1;
  string noticeId = 2;
  int64 startTime = 3;
  int64 endTime = 4;
  int32 priority = 5;
}
message IdolCard {
  string idolCardId = 2;
  penum.IdolCardLevelLimitRank levelLimitRank = 4;
  penum.IdolCardPotentialRank potentialRank = 5;
  bool isClearTrueEnd = 6;
}
message Meishi {
  string publicUserId = 1;
  MeishiBase meishiBase = 2;
  repeated MeishiObject objects = 3;
  string imagePath = 4;
  string timeline = 5;
}
message MeishiBase {
  int32 layoutNumber = 1;
  bool vertical = 2;
  string beforeIdolCardId = 10;
  string afterIdolCardId = 11;
  string supportCardId = 12;
  string meishiBaseAssetId = 13;
  string memoryAssetId = 14;
  string imagePath = 15;
  string moviePath = 16;
  string userMemoryId = 17;
  string userPhotoId = 18;
  string userMovieId = 19;
  string meishiBaseColorId = 20;
  string beforeIdolCardSkinId = 21;
  string afterIdolCardSkinId = 22;
}
message MeishiObject {
  penum.MeishiObjectType type = 1;
  string userName = 10;
  bool vertical = 11;
  bool displayPublicUserId = 20;
  string publicUserId = 21;
  bool displayPvpRateGrade = 22;
  penum.PvpRateGrade grade = 23;
  bool displayProducerLevel = 24;
  int32 producerLevel = 25;
  bool displayFanCount = 26;
  int64 fanCount = 27;
  bool displayComment = 28;
  string comment = 29;
  string achievementId = 40;
  Achievement achievement = 41;
  string meishiIllustrationAssetId = 50;
  string idolCardSkinId = 60;
  string supportCardId = 61;
  string produceCardId = 62;
  string produceItemId = 63;
  string produceDrinkId = 64;
  string imagePath = 65;
  string moviePath = 66;
  string userPhotoId = 67;
  string userMemoryId = 68;
  string userMovieId = 69;
  string meishiBaseAssetId = 70;
  string memoryAssetId = 71;
  string meishiTextColorId = 100;
  int32 positionX = 101;
  int32 positionY = 102;
  int32 size = 103;
  bool lock = 104;
  bool background = 105;
  int32 layer = 106;
  string metadata = 999;
}
message Memory {
  string userMemoryId = 1;
  string assetId = 2;
  string imagePath = 3;
  penum.ResultGrade grade = 4;
  int32 power = 5;
  string characterId = 6;
  string idolCardId = 7;
  string idolCardSkinId = 8;
  penum.ProducePlanType planType = 9;
  penum.IdolCardLevelLimitRank idolCardLevelLimitRank = 10;
  penum.IdolCardPotentialRank idolCardPotentialRank = 11;
  bool noProduceHistory = 12;
  bool isPrimaStella = 13;
  bool isHighScoreRush = 14;
  string researchId = 15;
  ProduceCard produceCard = 20;
  penum.ProduceMemoryProduceCardPhaseType produceCardPhaseType = 21;
  repeated MemoryAbility abilities = 22;
  int32 vocal = 30;
  int32 dance = 31;
  int32 visual = 32;
  int32 stamina = 33;
  repeated ProduceCard examBattleProduceCards = 34;
  repeated string examBattleProduceItemIds = 35;
}
message MemoryAbility {
  string id = 1;
  int32 level = 2;
}
message ProduceCampaign {
  penum.ProduceCampaignType type = 1;
  string name = 2;
  string description = 3;
  string assetId = 4;
  string produceGroupId = 5;
  string produceId = 6;
  int32 dailyCount = 7;
  int32 termCount = 8;
  int32 remainingCount = 9;
  bool isHalf = 20;
  int32 memoryRentalCount = 30;
  repeated Reward appealRewards = 40;
  int32 memoryRerollCount = 60;
  int64 startTime = 97;
  int64 endTime = 98;
  int32 order = 99;
}
message ProduceCard {
  string id = 1;
  int32 upgradeCount = 2;
  repeated ProduceCardCustomize customizes = 3;
  string produceCardSkinId = 100;
}
message ProduceCardConversion {
  string beforeProduceCardId = 1;
  string afterProduceCardId = 2;
}
message ProduceCardCustomize {
  string id = 1;
  int32 customizeCount = 2;
}
message ProduceConsumptionResult {
  penum.ProduceResourceType resourceType = 1;
  string resourceId = 2;
  int32 quantity = 3;
  int32 beforeQuantity = 4;
  int32 afterQuantity = 5;
}
message ProduceDescriptionSegment {
  penum.ProduceDescriptionType produceDescriptionType = 1;
  penum.ExamDescriptionType examDescriptionType = 2;
  penum.ProduceExamEffectType examEffectType = 3;
  penum.ProduceCardGrowEffectType produceCardGrowEffectType = 4;
  penum.ProduceCardCategory produceCardCategory = 5;
  penum.ProduceCardMovePositionType produceCardMovePositionType = 6;
  penum.ProduceStepType produceStepType = 7;
  penum.ProduceStepBusinessType produceStepBusinessType = 8;
  string text = 100;
  string targetId = 101;
  int32 targetLevel = 102;
  int32 effectValue1 = 103;
  int32 effectValue2 = 104;
  int32 effectCount = 105;
  int32 turn = 106;
  int32 costValue = 107;
  string produceDescriptionSwapId = 200;
  string originProduceExamTriggerId = 201;
  string originProduceExamEffectId = 202;
  string originProduceCardStatusEnchantId = 203;
  bool isCost = 210;
  bool isOnlyOutGame = 1000;
  bool changeColor = 1001;
}
message ProduceEffectResult {
  penum.ProduceEffectType effectType = 1;
  string produceEffectId = 2;
  ProduceTriggerOrigin origin = 3;
  int32 effectValue = 4;
  string effectTargetId = 5;
  int32 beforeMaxStamina = 6;
  int32 afterMaxStamina = 7;
  int32 beforeStamina = 8;
  int32 afterStamina = 9;
  int32 beforeProducePoint = 10;
  int32 afterProducePoint = 11;
  int32 beforeVoteCount = 21;
  int32 afterVoteCount = 22;
  int32 beforeStar = 23;
  int32 afterStar = 24;
  int32 beforeVocal = 12;
  int32 afterVocal = 13;
  int32 beforeDance = 14;
  int32 afterDance = 15;
  int32 beforeVisual = 16;
  int32 afterVisual = 17;
  repeated ProduceCard beforeProduceCards = 18;
  repeated ProduceCard afterProduceCards = 19;
  repeated ProduceRewardResult providedRewards = 20;
  int32 beforeHighScoreGold = 80;
  int32 afterHighScoreGold = 81;
  repeated int32 effectNumbers = 99;
  bool ineffective = 100;
}
message ProduceExamEndResult {
  penum.ProduceStepType stepType = 1;
  repeated string produceDrinkIds = 2;
  repeated ProduceItem produceItems = 3;
  int32 producePoint = 4;
  int32 stamina = 5;
  int32 maxStamina = 6;
  int32 resultTargetValue = 7;
  int32 successThreshold = 8;
  int32 resultTargetValueLimit = 9;
  repeated ExamTriggerCount examTriggerCounts = 10;
}
message ProduceHistory {
  string produceId = 1;
  int32 score = 2;
  penum.ResultGrade grade = 3;
  string userName = 4;
  int32 producerLevel = 5;
  int64 clearedTime = 6;
  string idolCardId = 7;
  string idolCardSkinId = 8;
  penum.IdolCardLevelLimitRank levelLimitRank = 9;
  penum.IdolCardPotentialRank potentialRank = 10;
  repeated penum.ProduceType trueEndProduceTypes = 11;
  repeated ProduceHistory.Audition auditions = 12;
  bool isPrimaStella = 13;
  repeated ProduceHistory.DeckSupportCard deckSupportCards = 20;
  repeated ProduceHistory.DeckMemory deckMemories = 21;
  repeated ProduceHistory.DeckProduceCard produceCards = 22;
  repeated string produceItemIds = 23;
  Memory memory = 24;
  int32 vocal = 30;
  int32 dance = 31;
  int32 visual = 32;
  int32 vocalGrowthRatePermil = 33;
  int32 danceGrowthRatePermil = 34;
  int32 visualGrowthRatePermil = 35;
  int32 maxStamina = 36;
  int32 voteCount = 37;
  int32 star = 38;
  repeated string produceCustomizeItemIds = 39;
  repeated ProduceSchedule schedules = 99;
  bool isHighScoreRush = 100;
  int32 highScoreGold = 101;
  string produceHighScoreId = 102;
  string researchId = 110;
  message Audition {
    penum.ProduceStepType stepType = 1;
    int32 stepSelectNumber = 2;
    int32 rank = 3;
    int32 score = 4;
    ExamContestSituation examContestSituation = 99;
  }
  message DeckMemory {
    Memory memory = 1;
    bool isRental = 2;
  }
  message DeckProduceCard {
    ProduceCard produceCard = 1;
    bool fromMemory = 2;
  }
  message DeckSupportCard {
    string id = 1;
    int32 level = 2;
    penum.SupportCardLevelLimitRank levelLimitRank = 3;
    bool isRental = 4;
  }
}
message ProduceHistoryCache {
  bytes userIdBytes = 1;
  bytes userMemoryIdBytes = 2;
  int32 score = 3;
}
message ProduceItem {
  string produceItemId = 1;
  int32 fireCount = 2;
}
message ProduceLessonGrowthResult {
  int32 vocal = 1;
  int32 dance = 2;
  int32 visual = 3;
  int32 hardBonusVocal = 4;
  int32 hardBonusDance = 5;
  int32 hardBonusVisual = 6;
  int32 growthRateBonusVocal = 7;
  int32 growthRateBonusDance = 8;
  int32 growthRateBonusVisual = 9;
  int32 auditionParameterGrowthRateVocal = 10;
  int32 auditionParameterGrowthRateDance = 11;
  int32 auditionParameterGrowthRateVisual = 12;
}
message ProduceMemoryRewardResult {
  repeated ProduceRewardResult providedRewards = 1;
  ProduceTriggerOrigin origin = 100;
}
message ProduceRewardResult {
  penum.ProduceResourceType resourceType = 1;
  string resourceId = 2;
  int32 resourceLevel = 3;
  int32 quantity = 4;
  repeated ProduceCardCustomize customizes = 5;
}
message ProduceSchedule {
  int32 number = 1;
  penum.ProduceStepType selectedStepType = 2;
  repeated penum.ProduceStepType stepTypes = 3;
  repeated penum.ProduceParameterType stepSubParameterTypes = 4;
  int32 refreshStamina = 5;
}
message ProduceTriggerOrigin {
  penum.ProduceTriggerOriginType originType = 1;
  string originOwnerId = 2;
  string originId = 3;
  int32 originLevel = 4;
}
message ProducerLevelUnlock {
  int32 level = 1;
  repeated ProducerLevelUnlockTarget targets = 2;
  Reward reward = 3;
  repeated Reward bonusRewards = 4;
}
message ProducerLevelUnlockTarget {
  penum.ProducerLevelUnlockType type = 1;
  string id = 2;
  int32 quantity = 3;
}
message ProducerRankingResult {
  string characterId = 1;
  repeated ProducerRankingResult.ProduceResult produceResults = 2;
  repeated ProducerRankingResult.TowerResult towerResults = 3;
  message ProduceResult {
    string produceGroupId = 1;
    int64 point = 2;
    int64 diff = 3;
  }
  message TowerResult {
    string towerId = 1;
    int64 layerNumber = 2;
    int64 point = 3;
    int64 diff = 4;
  }
}
message PvpRateExamBattleResult {
  ExamBattleAutoRequest examBattleAutoRequest = 1;
  repeated int32 selfStageResultScoreList = 2;
  repeated int32 rivalStageResultScoreList = 3;
}
message PvpRateSetupUnitStageFormation {
  penum.PvpRateStageType stage = 1;
  repeated PvpRateSetupUnitStageFormation.Slot slots = 2;
  message Slot {
    string mainUserMemoryId = 1;
    string subUserMemoryId = 2;
  }
}
message ResearchExchangeItemRewardResult {
  string researchId = 1;
  penum.ResourceType resourceType = 2;
  string resourceId = 3;
  int32 baseQuantity = 4;
  int32 bonusQuantity = 5;
  int32 bonusPermil = 6;
}
message ResearchPointResult {
  string researchId = 1;
  int32 beforePoint = 2;
  int32 afterPoint = 3;
  repeated ResearchPointReward allRewards = 4;
  repeated ResearchPointReward provideRewards = 5;
}
message ResearchPointReward {
  int32 point = 1;
  Reward reward = 2;
  bool feature = 3;
  bool repeat = 4;
  int32 repeatPoint = 5;
}
message Reward {
  penum.ResourceType resourceType = 1;
  string resourceId = 2;
  int32 quantity = 3;
}
message RewardResult {
  penum.ResourceType resourceType = 1;
  string resourceId = 2;
  int32 quantity = 3;
  int64 beforeQuantity = 4;
  int64 afterQuantity = 5;
  bool isNew = 6;
  bool isTruncate = 7;
  bool isGift = 8;
  bool isCampaign = 9;
  bool isItemEffect = 10;
}
message SelectionMemory {
  string userSelectionMemoryId = 1;
  string memoryTagId = 2;
  bool isProtected = 3;
  penum.ResultGrade grade = 4;
  string assetId = 5;
  string imagePath = 6;
  string produceId = 7;
  string characterId = 8;
  string idolCardId = 9;
  string idolCardSkinId = 10;
  penum.ProducePlanType planType = 11;
  penum.IdolCardLevelLimitRank idolCardLevelLimitRank = 12;
  penum.IdolCardPotentialRank idolCardPotentialRank = 13;
  bool isPrimaStella = 14;
  int32 startDearnessLevel = 15;
  repeated string activateProduceGrowthPanelIds = 16;
  repeated int32 activateProduceGrowthPanelLevels = 17;
  int32 vocal = 30;
  int32 dance = 31;
  int32 visual = 32;
  int32 vocalGrowthRatePermil = 33;
  int32 danceGrowthRatePermil = 34;
  int32 visualGrowthRatePermil = 35;
  int32 stamina = 36;
  int32 star = 37;
  repeated SelectionProduceCard produceCards = 50;
  repeated SelectionProduceItem produceItems = 51;
  repeated SelectionProduceCustomizeItem produceCustomizeItems = 52;
  repeated SelectionSupportCard supportCards = 53;
  repeated SelectionMemorySlot memories = 54;
  repeated ProduceSchedule schedules = 55;
  int32 lessonVocalSpChangeRatePermil = 70;
  int32 lessonDanceSpChangeRatePermil = 71;
  int32 lessonVisualSpChangeRatePermil = 72;
  int32 lessonPresentAdditionalProduceCardRewardCount = 73;
  int32 staminaRecoverValueRatePermil = 74;
  int32 staminaReduceValueRatePermil = 75;
  int32 producePointAdditionValueRatePermil = 76;
  int32 producePointReduceValueRatePermil = 77;
  int32 produceDrinkGetDisableTurn = 78;
  int32 produceItemGetDisableTurn = 79;
  int32 producePointGetDisableTurn = 80;
  int32 staminaRecoverDisableTurn = 81;
  int32 examExtraTurn = 82;
  int32 auditionNpcEnhancePermil = 83;
  int32 eventSchoolStaminaPermil = 84;
  int32 eventActivityProducePointPermil = 85;
  repeated string excludeProduceCardIds = 86;
  bool hiddenProduceCardReroll = 87;
  bool hiddenProduceCardExclude = 88;
  bool hiddenShopReroll = 89;
  int32 produceCardRemainSelectRerollCount = 90;
  int32 produceCardRemainExcludeCount = 91;
  int32 shopRemainRerollCount = 92;
  int32 vocalAdditionalLimit = 93;
  int32 danceAdditionalLimit = 94;
  int32 visualAdditionalLimit = 95;
  int32 useProduceCardCount = 200;
  int32 getProduceCardCount = 201;
  int32 upgradeProduceCardCount = 202;
  int32 customizeProduceCardCount = 203;
  string produceHighScoreId = 800;
  string researchId = 801;
  int64 clearedTime = 900;
  int64 lastUsedTime = 901;
}
message SelectionMemoryAbility {
  string id = 1;
  int32 level = 2;
  int32 triggerCount = 3;
}
message SelectionMemorySlot {
  int32 number = 1;
  string userMemoryId = 2;
  bool isRental = 3;
  Memory memory = 4;
  repeated SelectionMemoryAbility memoryAbilities = 5;
}
message SelectionProduceCard {
  ProduceCard produceCard = 1;
  bool fromMemory = 2;
}
message SelectionProduceCustomizeItem {
  string produceCustomizeItemId = 1;
  int32 triggerCount = 2;
  int32 reactionCount = 3;
}
message SelectionProduceItem {
  string id = 1;
  int32 triggerCount = 2;
  int32 reactionCount = 3;
}
message SelectionProduceSkill {
  string id = 1;
  int32 level = 2;
  int32 triggerCount = 3;
}
message SelectionSupportCard {
  int32 number = 1;
  string supportCardId = 2;
  int32 level = 3;
  penum.SupportCardLevelLimitRank levelLimitRank = 4;
  bool isRental = 5;
  repeated SelectionProduceSkill produceSkills = 6;
  repeated string eventDetailIds = 7;
}
message SimpleProfile {
  string publicUserId = 1;
  string name = 2;
  int32 level = 3;
  int64 lastLoginTime = 4;
  string comment = 6;
  Meishi meishi = 7;
  string badgeId = 8;
  bool isBlocked = 9;
}
message StartupNotification {
  string id = 1;
  penum.StartupNotificationType type = 2;
  penum.StartupNotificationEffectType effectType = 14;
  string horizontalMovieAssetId = 3;
  string verticalMovieAssetId = 4;
  string linkTitle = 5;
  penum.LinkType linkType = 6;
  string linkId = 7;
  string storyId = 8;
  string imageAssetId = 9;
  string noticeId = 10;
  string shopItemId = 11;
  int32 shopItemPurchasedCount = 12;
  int64 shopItemNextResetTime = 13;
  GashaPoint gashaPoint = 15;
  repeated GashaBanner gashaPointBanners = 16;
  string coinGashaItemId = 17;
  string exchangeItemId = 18;
  string playItemId = 22;
  string freeText = 23;
  string freeTextTitle = 24;
  string freeTextCloseButtonText = 25;
  int32 priority = 99;
}
message StoryEventBonus {
  repeated StoryEventBonus.CharacterBonus characterBonuses = 1;
  repeated StoryEventBonus.IdolCardBonus idolCardBonuses = 2;
  repeated StoryEventBonus.SupportCardBonus supportCardBonuses = 3;
  message CharacterBonus {
    repeated string characterIds = 1;
    int32 permil = 2;
    repeated penum.IdolCardRarity idolCardRarities = 3;
    repeated StoryEventBonus.CharacterBonus.PotentialRankBonusPermil potentialRankBonusPermils = 4;
    message PotentialRankBonusPermil {
      penum.IdolCardPotentialRank potentialRank = 1;
      int32 permil = 2;
    }
  }
  message IdolCardBonus {
    repeated string idolCardIds = 1;
    repeated StoryEventBonus.IdolCardBonus.PotentialRankBonusPermil potentialRankBonusPermils = 2;
    message PotentialRankBonusPermil {
      penum.IdolCardPotentialRank potentialRank = 1;
      int32 permil = 2;
    }
  }
  message SupportCardBonus {
    repeated string supportCardIds = 1;
    repeated StoryEventBonus.SupportCardBonus.LevelLimitRankBonusPermil levelLimitRankBonusPermils = 2;
    message LevelLimitRankBonusPermil {
      penum.SupportCardLevelLimitRank levelLimitRank = 1;
      int32 permil = 2;
    }
  }
}
message StoryEventPointReward {
  int32 point = 1;
  Reward reward = 3;
  bool feature = 4;
  bool repeat = 5;
  int32 repeatPoint = 6;
  bool displayTop = 7;
}
message StoryEventProduceResult {
  StoryEventProduceResult.PointResult pointResult = 1;
  StoryEventProduceResult.CoinResult coinResult = 2;
  repeated RewardResult rewardResults = 3;
  penum.StoryEventType storyEventType = 10;
  string titleAssetId = 11;
  string storyGroupId = 12;
  string gradationColor1 = 13;
  string gradationColor2 = 14;
  string backgroundAssetId = 15;
  string bgmAssetId = 16;
  string sceneLayoutId = 17;
  string sceneLayoutCollectionId = 18;
  string consumptionItemId = 19;
  message CoinResult {
    string storyEventId = 1;
    penum.ResourceType resourceType = 2;
    string resourceId = 3;
    int32 baseCoinQuantity = 4;
    int32 bonusCoinQuantity = 5;
    int32 bonusPermil = 6;
  }
  message PointResult {
    string storyEventId = 1;
    int32 bonusPermil = 2;
    int32 beforePoint = 3;
    int32 afterPoint = 4;
    repeated StoryEventPointReward allRewards = 5;
    repeated StoryEventPointReward provideRewards = 6;
  }
}
message SupportCard {
  string id = 1;
  int32 level = 2;
  penum.SupportCardLevelLimitRank levelLimitRank = 3;
}
message TowerLayerHistory {
  string userId = 1;
  string publicUserId = 2;
  string userName = 3;
  int32 producerLevel = 4;
  int32 clearRank = 5;
  int32 score = 6;
  repeated Memory memories = 7;
  bool isDefault = 8;
  int64 playTime = 9;
  repeated ProduceCardConversion produceCardConversions = 10;
}
