syntax = "proto3";
package ptransaction;
option go_package = "vertesan/campus/proto/ptransaction";
import "penum.proto";
import "pcommon.proto";

message User {
  string serverUserId = 3;
  string publicUserId = 2;
  int64 tutorialClearedTime = 7;
  bool receivedTutorialRewardIdolCard = 8;
  int64 forceTitleTransitionTime = 10;
  int64 readForceTitleTransitionTime = 11;
  string dmmGamesId = 101;
}
message UserActionPoint {
  int32 quantity = 2;
  int64 quantityUpdateTime = 3;
}
message UserAuthProvider {
  penum.AuthProviderType authProviderType = 2;
}
message UserBadge {
  string badgeId = 2;
}
message UserBalance {
  int32 freeBalance = 1;
  int32 paidBalance = 2;
}
message UserBanWarning {
  bool isConfirmationRequired = 2;
}
message UserCharacter {
  string characterId = 2;
  int64 fanCount = 3;
  repeated penum.ProduceType trueEndProduceTypes = 4;
  int32 dearnessPoint = 7;
}
message UserCharacterCostume {
  string characterId = 2;
  penum.CostumeSetType setType = 3;
  string costumeHeadId = 5;
  string costumeId = 4;
  bool useDefaultCostumeHead = 6;
  repeated string excludeCostumeIds = 7;
  repeated string excludeCostumeHeadIds = 8;
}
message UserCharacterRoster {
  string characterId = 2;
  bool viewedPlayable = 3;
}
message UserComeback {
  string comebackId = 2;
  int64 endTime = 4;
}
message UserCompetition {
  penum.CompetitionGrade grade = 3;
  penum.CompetitionGrade bestGrade = 4;
  int64 lastPlayTime = 5;
  int64 remainingPlayCount = 7;
  int64 remainingContinueCount = 9;
  bool isInitializedCurrentSeason = 10;
  penum.CompetitionStageType stageType = 101;
  penum.CompetitionPhaseType phaseType = 102;
  bool isAuto = 103;
}
message UserCompetitionDeck {
  int32 number = 2;
  string name = 3;
  repeated pcommon.CompetitionDeckSetupMemorySlot memorySlots = 100;
}
message UserCompetitionSeasonDeck {
  penum.CompetitionStageType stageType = 2;
  repeated pcommon.CompetitionDeckSetupMemorySlot slots = 100;
}
message UserCostume {
  string costumeId = 2;
  bool checked = 3;
}
message UserCostumeHead {
  string costumeHeadId = 2;
  bool checked = 3;
}
message UserCount {
  penum.CountType type = 2;
  int64 totalCount = 3;
  int64 dailyCount = 4;
  int64 updatedTime = 5;
}
message UserDearnessStory {
  string characterId = 2;
  int32 dearnessLevel = 3;
  bool satisfyDearnessProduceConditionSet = 4;
  int64 readTime = 5;
  bool read = 6;
  bool itemUnlocked = 7;
}
message UserGashaButton {
  string gashaId = 2;
  string gashaButtonId = 3;
  int64 lastDrawnTime = 4;
  int32 todayDrawCount = 5;
  int32 totalDrawCount = 6;
  int32 discountTodayDrawCount = 7;
  int32 discountTotalDrawCount = 8;
  int32 redrawCount = 9;
  int32 dailyLoginAccumulateCount = 10;
  int32 discountDailyLoginAccumulateCount = 11;
}
message UserGuild {
  penum.GuildJoinType joinType = 999;
}
message UserHomeCharacter {
  penum.HomeType homeType = 2;
  string characterId = 3;
  bool isRandom = 4;
}
message UserIdolCard {
  string idolCardId = 2;
  penum.IdolCardLevelLimitRank levelLimitRank = 3;
  penum.IdolCardPotentialRank potentialRank = 4;
  string idolCardSkinId = 5;
  int64 primaStellaUpgradedTime = 10;
  int64 createdTime = 999;
}
message UserIdolCardSkin {
  string idolCardSkinId = 2;
}
message UserInvitation {
  int64 totalInvitationPoint = 2;
  int64 receivedInvitationPointRewardThreshold = 3;
  bool isCodeEntered = 5;
  int64 codeEntryEndTime = 6;
}
message UserItem {
  string itemId = 2;
  int64 expiryTime = 3;
  int64 quantity = 4;
}
message UserMeishi {
  int32 number = 2;
  string imagePath = 3;
  repeated string useUserMemoryIds = 4;
  repeated string useUserPhotoIds = 5;
  repeated string useUserMovieIds = 6;
  string timeline = 7;
  int32 baseLayoutNumber = 100;
  string baseUserMemoryId = 117;
  string baseUserPhotoId = 118;
  string baseUserMovieId = 119;
}
message UserMeishiBaseAsset {
  string meishiBaseAssetId = 2;
}
message UserMeishiIllustrationAsset {
  string meishiIllustrationAssetId = 2;
}
message UserMemory {
  string userMemoryId = 2;
  string memoryTagId = 4;
  bool isProtected = 5;
  string assetId = 6;
  string imagePath = 7;
  penum.ResultGrade grade = 8;
  int32 power = 9;
  string produceId = 10;
  string characterId = 11;
  string idolCardId = 12;
  string idolCardSkinId = 13;
  penum.ProducePlanType planType = 14;
  penum.IdolCardLevelLimitRank idolCardLevelLimitRank = 15;
  penum.IdolCardPotentialRank idolCardPotentialRank = 16;
  int64 shotTime = 17;
  bool noProduceHistory = 18;
  int32 inheritCount = 19;
  pcommon.ProduceCard produceCard = 22;
  penum.ProduceMemoryProduceCardPhaseType produceCardPhaseType = 23;
  repeated UserMemory.MemoryAbility abilities = 26;
  int32 vocal = 30;
  int32 dance = 31;
  int32 visual = 32;
  int32 stamina = 33;
  repeated pcommon.ProduceCard examBattleProduceCards = 36;
  repeated string examBattleProduceItemIds = 37;
  string researchId = 50;
  int32 researchRerollCount = 51;
  bool isResearchFavorite = 52;
  bool isPrimaStella = 60;
  penum.ProduceLiveType endingLiveType = 99;
  penum.ProduceLiveType produceLiveType = 100;
  string liveCostumeId = 101;
  string liveCostumeHeadId = 102;
  int32 reshootingCount = 103;
  string musicId = 104;
  bool isHighScoreRush = 105;
  repeated UserMemory.UnitCharacter unitCharacters = 120;
  bool useCharacterFocusCamera = 121;
  message MemoryAbility {
    string id = 1;
    int32 level = 2;
  }
  message UnitCharacter {
    string characterId = 1;
    string liveCostumeId = 2;
    string liveCostumeHeadId = 3;
  }
}
message UserMemoryInherit {
  string userMemoryId = 2;
  repeated pcommon.ProduceCard examBattleProduceCards = 4;
}
message UserMission {
  string missionId = 2;
  int64 progress = 3;
  repeated int64 receivedThresholds = 4;
  bool isUnlock = 5;
  int64 firstThresholdClearTime = 6;
}
message UserMissionDailyReleaseGroup {
  string missionDailyReleaseGroupId = 2;
  int64 startTime = 3;
}
message UserMissionGroup {
  string missionGroupId = 2;
  bool received = 3;
}
message UserMissionPass {
  string missionPassId = 2;
  repeated int32 receivedNormalThresholds = 4;
  repeated int32 receivedPremiumThresholds = 5;
  bool hasPremiumPass = 6;
  bool providedReceivedWeeklyMissionPassPoint = 7;
}
message UserMissionPassPoint {
  string missionPassId = 2;
  string missionPassPointId = 3;
  int32 point = 4;
}
message UserMissionPoint {
  string missionPointId = 2;
  int32 point = 3;
  repeated int32 receivedPoints = 4;
}
message UserMoney {
  int32 unreceivedTotalQuantity = 2;
  int32 unreceivedTotalElapsedTimeSeconds = 3;
  int64 lastReceivedTime = 4;
}
message UserMovie {
  string userMovieId = 2;
  string moviePath = 3;
  int32 retakeCount = 4;
  int32 meishiNumber = 5;
}
message UserMusic {
  string musicId = 2;
}
message UserPhoto {
  string userPhotoId = 2;
  string imagePath = 3;
  string idolCardId = 4;
  string name = 5;
  int64 shotTime = 6;
  bool isProtected = 7;
  repeated string characterIds = 8;
  string photoBackgroundId = 9;
  int64 reshootingCount = 10;
}
message UserPhotoBackground {
  string photoBackgroundId = 2;
}
message UserPhotoPose {
  string photoPoseId = 2;
}
message UserPlayGames {
  repeated string playGamesAchievementIds = 10;
  repeated int64 playGamesAchievementProgresses = 11;
}
message UserPreference {
  penum.PhotoButtonExecuteType photoButtonExecuteType = 2;
  bool produceDisableForceLiveCommon = 3;
  bool produceNextIdolAuditionProEasyMode = 4;
  bool produceDisableSupportCardEventProduceCardUpgrade = 5;
}
message UserProduce {
  string produceId = 2;
  int32 playCount = 3;
  int32 clearCount = 4;
}
message UserProduceAdv {
  string assetId = 2;
}
message UserProduceCard {
  string produceCardId = 2;
  int32 produceCardUpgradeCount = 3;
}
message UserProduceCardConversion {
  string beforeProduceCardId = 2;
  string afterProduceCardId = 3;
  bool enable = 4;
}
message UserProduceCardReward {
  string produceCardId = 2;
}
message UserProduceCardSkin {
  string produceCardSkinId = 2;
}
message UserProduceCardSkinPreference {
  string produceCardId = 2;
  string produceCardSkinId = 3;
  repeated UserProduceCardSkinPreference.CharacterProduceCardSkin characterProduceCardSkins = 5;
  message CharacterProduceCardSkin {
    string characterId = 1;
    string produceCardSkinId = 2;
  }
}
message UserProduceCharacter {
  string characterId = 2;
  string produceId = 3;
  int32 playCount = 5;
  int32 clearCount = 6;
  int32 unlockChallengeSlotNumber = 7;
  int32 highestScore = 8;
}
message UserProduceDrink {
  string produceDrinkId = 2;
}
message UserProduceGroupCharacter {
  string characterId = 2;
  string produceGroupId = 3;
  repeated penum.ProduceStepAuditionType viewUnlockAnimationAuditionTypes = 4;
  penum.ProduceLiveType endingLiveType = 5;
  bool disableForceLiveCommon = 6;
  bool enableProduceCharacterUnitOverrideLiveCostume = 7;
}
message UserProduceGrowthPanel {
  string produceGrowthPanelId = 2;
  int32 level = 3;
  bool enable = 4;
}
message UserProduceIdolCard {
  string produceId = 2;
  string idolCardId = 3;
  int32 clearCount = 5;
  int32 highestScore = 6;
  int32 seasonHighestScore = 7;
  repeated string challengeProduceItemIds = 10;
  penum.ProduceLiveType liveType = 11;
  int32 eventHighestScore = 12;
}
message UserProduceItem {
  string produceItemId = 2;
}
message UserProduceLive {
  string musicId = 2;
  penum.ProduceLiveType liveType = 3;
  bool viewed = 4;
  repeated string unlockCharacterIds = 5;
  repeated string viewedCharacterIds = 6;
}
message UserProduceMemoryDeck {
  penum.ProduceType produceType = 2;
  int32 number = 3;
  repeated string userMemoryIds = 4;
  string name = 5;
}
message UserProduceProgress {
  string produceGroupId = 2;
  string produceId = 3;
  int32 producerLevel = 5;
  string characterId = 6;
  string idolCardId = 7;
  string idolCardSkinId = 8;
  penum.IdolCardLevelLimitRank idolCardLevelLimitRank = 9;
  penum.IdolCardPotentialRank idolCardPotentialRank = 10;
  repeated string satisfiedConditionSetIds = 11;
  repeated string produceBoostItemIds = 12;
  repeated penum.ProduceType trueEndProduceTypes = 13;
  bool hasForceLiveCommonIdolCard = 15;
  bool disableForceLiveCommon = 16;
  bool isInterrupted = 18;
  bool hasInterruptedBefore = 19;
  int32 startDearnessLevel = 20;
  bool isPrimaStella = 21;
  string userSelectionMemoryId = 24;
  repeated UserProduceProgress.ProduceCardSkin produceCardSkins = 27;
  bool enableProduceCharacterUnitOverrideLiveCostume = 28;
  bool isResearch = 71;
  repeated string researchExternalProduceCardIds = 72;
  repeated string researchMemoryPickupProduceCardIds = 73;
  repeated string researchProduceItemIds = 74;
  bool researchMemoryProduceCardPickupDisable = 75;
  string produceHighScoreId = 80;
  repeated pcommon.ProduceCampaign produceCampaigns = 91;
  penum.ProduceProgressStatus status = 100;
  int32 produceScore = 101;
  bool isFailedProduce = 102;
  int32 stepNumber = 103;
  penum.ProduceStepType stepType = 105;
  string stepId = 106;
  penum.ProduceStepType effectStepType = 107;
  string effectStepId = 108;
  int32 stepSelectNumber = 109;
  penum.ProduceStepType originStepType = 110;
  bool inProgressStep = 112;
  int32 continueCount = 113;
  int32 produceNavigationNormalNumber = 114;
  int32 produceNavigationAuditionNumber = 115;
  int32 produceNavigationLoseNumber = 116;
  pcommon.Memory resultMemory = 118;
  int32 lastProduceEventCharacterGrowthNumber = 121;
  bool isChangeCostumeProduce = 123;
  bool isChangeCostumeLive = 124;
  bool isChangeCostumeTraining = 126;
  string rentalPublicUserId = 125;
  repeated string changeCostumeLiveUnitCharacterIds = 127;
  repeated string changeCostumeTrainingUnitCharacterIds = 128;
  repeated int32 liveAdditionalAssetNumbers = 129;
  pcommon.SelectionMemory resultSelectionMemory = 131;
  int32 vocal = 200;
  int32 dance = 201;
  int32 visual = 202;
  int32 vocalGrowthRatePermil = 203;
  int32 danceGrowthRatePermil = 204;
  int32 visualGrowthRatePermil = 205;
  int32 vocalAdditionalLimit = 206;
  int32 danceAdditionalLimit = 207;
  int32 visualAdditionalLimit = 208;
  int32 stamina = 220;
  int32 maxStamina = 221;
  int32 staminaRecoverValueRatePermil = 222;
  int32 staminaReduceValueRatePermil = 223;
  int32 staminaRecoverDisableTurn = 224;
  int32 producePoint = 230;
  int32 producePointAdditionValueRatePermil = 231;
  int32 producePointReduceValueRatePermil = 232;
  int32 producePointGetDisableTurn = 233;
  int32 voteCount = 235;
  int32 highScoreGold = 236;
  int32 star = 237;
  int32 starPermil = 238;
  repeated UserProduceProgress.ProduceSkill characterProduceSkills = 253;
  int32 dearnessStoryDearnessLevel = 254;
  repeated UserProduceProgress.ProduceSkill idolCardProduceSkills = 273;
  int32 produceCardRemainSelectRerollCount = 311;
  bool hiddenProduceCardReroll = 312;
  repeated string excludeProduceCardIds = 313;
  int32 produceCardRemainExcludeCount = 314;
  bool hiddenProduceCardExclude = 315;
  int32 produceCardAdditionalLegendCount = 317;
  repeated string convertProduceCardIds = 318;
  repeated UserProduceProgress.ProduceItem produceItems = 353;
  int32 produceItemGetDisableTurn = 354;
  repeated string produceDrinkIds = 400;
  int32 produceDrinkGetDisableTurn = 401;
  int32 produceDrinkPossessAdditionalCount = 404;
  int32 auditionEffectParameterBonusPermil = 504;
  int32 auditionNpcEnhancePermil = 505;
  int32 auditionParameterGrowthRatePermil = 508;
  repeated UserProduceProgress.AuditionResult auditions = 510;
  int32 eventSchoolStaminaPermil = 550;
  int32 eventActivityProducePointPermil = 551;
  int32 eventBusinessVoteCountPermil = 552;
  int32 examSeedValue = 600;
  string produceExamGimmickEffectGroupId = 601;
  repeated UserProduceProgress.ExamStatusEnchant examStatusEnchants = 607;
  int32 lessonVocalSpChangeRatePermil = 608;
  int32 lessonDanceSpChangeRatePermil = 609;
  int32 lessonVisualSpChangeRatePermil = 610;
  penum.ProduceExamResultType examResultType = 616;
  pcommon.ProduceLessonGrowthResult lessonGrowthResult = 618;
  pcommon.ProduceExamEndResult examEndResult = 620;
  int32 lessonLimitUpScore = 622;
  int32 examExtraTurn = 625;
  repeated UserProduceProgress.SelfLessonTypeStaminaPermil selfLessonTypeStaminaPermils = 627;
  repeated UserProduceProgress.ExamStatusEnchant examPermanentLessonStatusEnchants = 633;
  repeated UserProduceProgress.ExamStatusEnchant examPermanentAuditionStatusEnchants = 639;
  penum.ProduceLiveType liveType = 650;
  int32 lessonPresentAdditionalProduceCardRewardCount = 700;
  int32 customizeAdditionalProduceCardCount = 760;
  repeated int32 customizeDiscountPermils = 761;
  bool enableIdolCardProduceCardCustomize = 762;
  int32 shopProduceCardUpgradePrice = 800;
  int32 shopProduceCardDeletePrice = 801;
  repeated int32 shopDiscountPermils = 802;
  repeated int32 shopProduceCardUpgradeDiscountPermils = 803;
  repeated int32 shopProduceCardDeleteDiscountPermils = 804;
  repeated UserProduceProgress.ShopProduceCardDiscount shopProduceCardDiscounts = 807;
  repeated int32 shopProduceDrinkDiscountPermils = 808;
  int32 shopRemainRerollCount = 811;
  bool hiddenShopReroll = 812;
  int32 intervalCurrentProduceCardUpgradeCount = 831;
  int32 intervalRerollPrice = 832;
  repeated string satisfyProduceExamTriggerIds = 852;
  message AuditionResult {
    penum.ProduceStepType auditionStepType = 1;
    int32 selectNumber = 2;
    int32 rank = 3;
    int32 score = 4;
    int32 point = 5;
  }
  message ExamStatusEnchant {
    penum.ProduceTriggerOriginType originType = 1;
    string originOwnerId = 2;
    string originId = 3;
    int32 originLevel = 4;
    string id = 5;
  }
  message ProduceCardSkin {
    string produceCardId = 1;
    string produceCardSkinId = 2;
  }
  message ProduceItem {
    string produceItemId = 1;
    int32 fireCount = 2;
    int32 reactionCount = 3;
  }
  message ProduceSkill {
    string id = 1;
    int32 level = 2;
    int32 triggerCount = 3;
  }
  message SelfLessonTypeStaminaPermil {
    penum.ProduceStepLessonType lessonType = 1;
    int32 permil = 2;
  }
  message ShopProduceCardDiscount {
    string produceCardSearchId = 1;
    repeated int32 permils = 2;
  }
}
message UserProduceProgressAudition {
  penum.ProduceProgressAuditionStatusType status = 2;
  int32 vocalPermil = 3;
  int32 dancePermil = 4;
  int32 visualPermil = 5;
  int32 voteBonusPermil = 6;
  int32 starBonusPermil = 7;
  int32 stepSelectNumber = 99;
  int32 rank = 100;
  int32 score = 101;
  int32 stamina = 102;
  repeated string produceDrinkIds = 104;
  repeated string produceItemIds = 105;
  repeated int32 produceItemFireCounts = 106;
  int32 examSkipCount = 107;
  int32 point = 113;
  repeated pcommon.AuditionNpcResult auditionNpcs = 117;
}
message UserProduceProgressBusiness {
  penum.ProduceStepBusinessType businessType = 2;
  int32 number = 3;
  string name = 4;
  int32 destinationNumber = 5;
  int32 producePoint = 6;
  int32 stamina = 7;
  int32 excellentPermil = 8;
  string produceStepEventDetailId = 9;
  string excellentProduceStepEventDetailId = 10;
}
message UserProduceProgressEffect {
  int32 number = 2;
  repeated int32 numbers = 3;
  penum.ProduceEffectType type = 4;
  int32 value = 5;
  repeated UserProduceProgressEffect.Reward rewards = 10;
  repeated int32 researchExternalIndexes = 11;
  penum.ProducePickRangeType pickRangeType = 13;
  int32 pickCountMin = 14;
  int32 pickCountMax = 15;
  repeated int32 pickIndexes = 17;
  repeated int32 pickIndexes2 = 20;
  repeated string activatedProduceItemIds = 18;
  bool isNext = 26;
  string produceEffectId = 27;
  penum.ProduceTriggerOriginType originType = 28;
  string originId = 29;
  int32 originLevel = 30;
  string originOwnerId = 31;
  repeated string originProduceTriggerIds = 32;
  message Reward {
    penum.ProduceResourceType resourceType = 1;
    string resourceId = 2;
    int32 resourceLevel = 3;
    int32 quantity = 4;
  }
}
message UserProduceProgressEvent {
  string produceStepEventDetailId = 2;
  int32 number = 3;
  int64 suggestionIndex = 4;
  bool success = 5;
}
message UserProduceProgressInterval {
  int32 positionNumber = 2;
  bool purchased = 3;
  penum.ProduceResourceType resourceType = 4;
  string resourceId = 5;
  int32 upgradeCount = 6;
  int32 staminaRecoverValue = 7;
  int32 price = 8;
  int32 nextPrice = 9;
}
message UserProduceProgressMemory {
  int32 number = 2;
  string userMemoryId = 3;
  bool isRental = 5;
  repeated UserProduceProgressMemory.MemoryAbility abilities = 28;
  pcommon.Memory memory = 100;
  message MemoryAbility {
    string id = 1;
    int32 level = 2;
    int32 triggerCount = 3;
    bool disable = 4;
  }
}
message UserProduceProgressPresent {
  int32 positionNumber = 2;
  bool received = 3;
  penum.ProduceDisplayType displayType = 4;
  int32 rewardCount = 5;
  int32 pickCount = 6;
  repeated UserProduceProgressPresent.Reward rewards = 11;
  repeated int32 rewardIndexes = 12;
  bool isVoteBonus = 14;
  repeated int32 researchExternalIndexes = 15;
  message Reward {
    penum.ProduceResourceType resourceType = 1;
    string resourceId = 2;
    int32 resourceLevel = 3;
    int32 quantity = 4;
  }
}
message UserProduceProgressProduceCard {
  int32 number = 2;
  string produceCardId = 3;
  int32 upgradeCount = 4;
  bool deleted = 6;
  penum.ProduceResourceOriginType originType = 7;
  repeated pcommon.ProduceCardCustomize customizes = 10;
  bool customizing = 11;
  string produceCardSkinId = 20;
}
message UserProduceProgressProduceCustomizeItem {
  int32 number = 2;
  string produceCustomizeItemId = 3;
  int32 triggerCount = 4;
  int32 reactionCount = 5;
}
message UserProduceProgressSchedule {
  int32 stepNumber = 2;
  int32 addStepLevel = 3;
  string vocalProduceStepSelfLessonId = 30;
  string vocalSpProduceStepSelfLessonId = 31;
  string danceProduceStepSelfLessonId = 33;
  string danceSpProduceStepSelfLessonId = 34;
  string visualProduceStepSelfLessonId = 36;
  string visualSpProduceStepSelfLessonId = 37;
  string legendVocalProduceStepLessonId = 51;
  string legendVocalSpProduceStepLessonId = 52;
  string legendDanceProduceStepLessonId = 54;
  string legendDanceSpProduceStepLessonId = 55;
  string legendVisualProduceStepLessonId = 57;
  string legendVisualSpProduceStepLessonId = 58;
  string vocalProduceStepOpenLessonId = 60;
  string vocalSpProduceStepOpenLessonId = 61;
  string vocalStarProduceStepOpenLessonId = 62;
  string vocalSpStarProduceStepOpenLessonId = 63;
  string danceProduceStepOpenLessonId = 65;
  string danceSpProduceStepOpenLessonId = 66;
  string danceStarProduceStepOpenLessonId = 67;
  string danceSpStarProduceStepOpenLessonId = 68;
  string visualProduceStepOpenLessonId = 70;
  string visualSpProduceStepOpenLessonId = 71;
  string visualStarProduceStepOpenLessonId = 72;
  string visualSpStarProduceStepOpenLessonId = 73;
  repeated penum.ProduceStepType stepTypes = 24;
  repeated penum.ProduceParameterType stepSubParameterTypes = 23;
  penum.ProduceStepType selectedStepType = 25;
  penum.ProduceExamResultType examResultType = 26;
  int32 refreshStamina = 27;
  int32 auditionRank = 28;
  repeated pcommon.AuditionNpcResult auditionNpcs = 83;
  int32 stepSelectNumber = 41;
  int32 maxAuditionStepSelectNumber = 42;
}
message UserProduceProgressShop {
  int32 positionNumber = 2;
  bool purchased = 3;
  penum.ProduceResourceType resourceType = 4;
  string resourceId = 5;
  int32 upgradeCount = 6;
  int32 price = 7;
  int32 discountPermil = 8;
  repeated int32 effectDiscountPermils = 9;
  repeated int32 effectResourceDiscountPermils = 10;
  int32 nextPrice = 11;
  bool lock = 12;
  bool highScoreReward = 13;
}
message UserProduceProgressSupportCard {
  int32 number = 2;
  bool isRental = 4;
  string supportCardId = 5;
  int32 level = 6;
  penum.SupportCardLevelLimitRank levelLimitRank = 7;
  repeated string produceSkillIds = 8;
  repeated int64 produceSkillLevels = 9;
  repeated int64 produceSkillTriggerCounts = 10;
  repeated UserProduceProgressSupportCard.ProduceSkill produceSkills = 11;
  int32 eventStaminaRecoverUpPermil = 12;
  int32 eventProducePointAdditionValueUpPermil = 13;
  int32 eventParameterAdditionValueUpPermil = 14;
  int32 eventProbabilityUpPermyriad = 15;
  int32 produceCardUpgradePermil = 16;
  bool eventProduceCardUpgrade = 18;
  message ProduceSkill {
    string id = 1;
    int32 level = 2;
    int32 triggerCount = 3;
  }
}
message UserProduceRerollMemory {
  int32 number = 2;
  pcommon.Memory resultMemory = 4;
}
message UserProduceStartAchievement {
  string achievementId = 2;
  int64 progress = 3;
}
message UserProduceStory {
  string storyId = 2;
  bool read = 4;
}
message UserProduceSupportCardDeck {
  penum.ProduceType produceType = 2;
  int32 number = 3;
  repeated string supportCardIds = 4;
  string name = 5;
}
message UserProfile {
  string name = 2;
  int32 bornMonth = 4;
  int32 bornDay = 5;
  int64 lastBirthdayUpdatedTime = 6;
  string supportCardId = 7;
  string userMemoryId = 8;
  string comment = 9;
  int64 exp = 10;
  int64 totalFanCount = 11;
  int32 additionFollowLimitCount = 12;
  int32 selectedMeishiNumber = 13;
  int32 maxPvpRateUnitPower = 14;
  int32 maxCompetitionDeckPower = 16;
  string badgeId = 17;
}
message UserPvpRate {
  penum.PvpRateGrade grade = 3;
  penum.PvpRateGrade bestGrade = 4;
  bool isInitializedCurrentSeason = 5;
  penum.PvpRatePhaseType phaseType = 100;
  int64 rivalMatchTime = 101;
  int32 supportBonusPermyriad = 104;
}
message UserPvpRateDeck {
  int32 number = 2;
  string name = 3;
  string mainUserMemoryId = 4;
  string subUserMemoryId = 5;
}
message UserPvpRateUnit {
  repeated pcommon.PvpRateSetupUnitStageFormation stageFormations = 3;
}
message UserShopItem {
  string shopItemId = 2;
  int64 lastPurchaseTime = 3;
  int64 purchasedCount = 4;
}
message UserStory {
  string storyId = 2;
  bool isUnlocked = 4;
  bool read = 6;
}
message UserSupportCard {
  string supportCardId = 2;
  int32 stockQuantity = 3;
  int32 level = 4;
  penum.SupportCardLevelLimitRank levelLimitRank = 5;
  int64 createdTime = 999;
}
message UserTime {
  penum.TimeType timeType = 2;
  int64 dataOfTime = 3;
}
message UserTower {
  string towerId = 2;
  int32 layerCount = 3;
  int32 clearLayerCount = 4;
  int32 totalClearRank = 5;
  int32 receivedLayerCount = 6;
  repeated string userMemoryIds = 11;
}
message UserTutorial {
  penum.TutorialType type = 2;
  int32 step = 3;
}
message UserWebStore {
  string latestCompletedUserPurchaseTransactionId = 11;
  string readUserPurchaseTransactionId = 12;
}
message UserWork {
  penum.WorkType type = 2;
  int32 durationMinutes = 3;
  int32 level = 4;
  string characterId = 5;
  int32 characterDearnessLevel = 6;
  int64 startedTime = 7;
  int64 lastSkippedTime = 8;
  int32 skipCount = 9;
  int32 totalFinishCount = 10;
  bool fixedIsExcellent = 11;
}
message UserWorkCharacter {
  string characterId = 2;
  bool isFine = 4;
  int32 totalFinishCount = 9;
}
